# Generated by Django 4.2.4 on 2023-08-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
