# Generated by Django 4.2.4 on 2023-08-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rent_date',
            new_name='borrow_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rent_period',
            new_name='borrow_period',
        ),
    ]
