services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn LMS.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
