# Generated by Django 4.2.4 on 2023-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField(max_length=8)),
            ],
        ),
    ]
