# Generated by Django 4.2.4 on 2023-08-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_birthdate_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1234, max_length=8),
        ),
    ]
