# Generated by Django 4.2.4 on 2023-08-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
    ]
