# Generated by Django 4.2.4 on 2023-08-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
    ]
