# Generated by Django 4.2.4 on 2023-08-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_rename_name_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='name',
        ),
    ]
