# Generated by Django 4.2.4 on 2023-08-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_rename_username_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
